### ISSUE TITLE
stop in run iteration function

### ISSUE THREAD

**Issue by xiao-song2022** [Valassis-Digital-Media/spylon#55]
import breeze.linalg._
var a = DenseVector(1,5,3,7,4,2,7,8,2,4,6,9,3,3,76,8)
def dif(X:DenseVector[Int] , k:Int){if (k==0) println(X) else {dif(X(1 until X.size) – X(0 until X.size – 1), k-1 ) } }
dif(a,5)

stop in the third sentence

**Comment by xiao-song2022** [comment]
jupyter error:
[MetaKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "C:\Users\86131\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel\kernelbase.py", line 406, in dispatch_shell
    await result
  File "C:\Users\86131\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel\kernelbase.py", line 726, in execute_request
    allow_stdin,
  File "C:\Users\86131\AppData\Local\Programs\Python\Python37\lib\site-packages\metakernel\_metakernel.py", line 397, in do_execute
    retval = self.do_execute_direct(code)
  File "C:\Users\86131\AppData\Local\Programs\Python\Python37\lib\site-packages\spylon_kernel\scala_kernel.py", line 141, in do_execute_direct
    res = self._scalamagic.eval(code.strip(), raw=False)
  File "C:\Users\86131\AppData\Local\Programs\Python\Python37\lib\site-packages\spylon_kernel\scala_magic.py", line 159, in eval
    res = intp.interpret(code.strip())
  File "C:\Users\86131\AppData\Local\Programs\Python\Python37\lib\site-packages\spylon_kernel\scala_interpreter.py", line 415, in interpret
    pyres = self.jbyteout.toByteArray().decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa8 in position 133: invalid start byte

**Comment by xiao-song2022** [comment]
i solve this problem by change — to -
